# Alternate site name
alternate: Tianciã®å°çª

open_graph:
  #twitter_id:
  #google_plus:
  #fb_admins:
  #fb_app_id:

# Assets
statics: / #//cdn.jsdelivr.net/gh/username/RepositoryName@latest/
css: css
js: js
images: images

# themes/shoka/source/images/***
favicon:
  apple_touch_icon: /apple-touch-icon.png
  #safari_pinned_tab: /logo.svg
  #android_manifest: /manifest.json
  #ms_browserconfig: /browserconfig.xml

# Dark Mode
# By default, the page judges whether to turn on the dark mode according to the device settings or user selection
# if `true`, the page will be displayed directly as Dark Mode, unless the user makes another choice
darkmode: false

# é»˜è®¤æƒ…å†µä¸‹ï¼Œå†æ¬¡æ‰“å¼€é¡µé¢æ—¶ï¼Œä¼šè‡ªåŠ¨æ»šåŠ¨åˆ°ä¸Šæ¬¡æµè§ˆçš„ä½ç½®ã€‚
# è¿™ä¸ªé€‰é¡¹è®¾ä¸º false æ—¶å°†åœç”¨æ­¤åŠŸèƒ½ã€‚
auto_scroll: true

#  æ˜¯å¦æ˜¾ç¤ºé¡µé¢åŠ è½½åŠ¨ç”» loading-cat
loader:
  start: false # å½“åˆæ¬¡æ‰“å¼€é¡µé¢æ—¶ï¼Œæ˜¾ç¤ºåŠ è½½åŠ¨ç”»
  switch: false # åˆ‡æ¢åˆ°å…¶ä»–é¡µé¢æ—¶ï¼Œæ˜¾ç¤ºåŠ è½½åŠ¨ç”»

# click with Firework
fireworks:
  enable: true
  color:
    # - "rgba(255,182,185,.9)"
    # - "rgba(250,227,217,.9)"
    # - "rgba(187,222,214,.9)"
    # - "rgba(138,198,209,.9)"

font:
  enable: true
  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: x.x`. Use `em` as unit. Default: 1 (16px)

  # Global font settings used for all elements inside <body>.
  global:
    external: true
    family: Mulish
    size:

  # Font settings for alternate title.
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5

  # Font settings for site title.
  title:
    external: true
    family: Noto Serif JP
    size: 2.5

  # Font settings for headlines (<h1> to <h6>).
  headings:
    external: true
    family: Noto Serif SC
    size:

  # Font settings for posts.
  posts:
    external: true
    family:

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family: Inconsolata

# project of https://www.iconfont.cn/
# //at.alicdn.com/t/font_1832207_c8i9n1ulxlt.css => 1832207_c8i9n1ulxlt
iconfont: "1832207_c8i9n1ulxlt"

menu:
  home: / || home
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  tianci: https://lovetianci.cn || heart
  # about: /about/ || user
  # friends: /friends/ || heart
  # talk: /talk/ || magic

# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/2016838087 || github || "#191717"
  #google: https://plus.google.com/yourname || google
  #twitter: https://twitter.com/yourname || twitter || "#00aff0"
  #zhihu: https://www.zhihu.com/people/yourname || zhihu || "#1e88e5"
  #music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  #weibo: https://weibo.com/yourname || weibo || "#ea716e"
  #about: https://about.me/yourname || address-card || "#3b5998"
  #email: mailto:yourname@mail.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

sidebar:
  # Sidebar Position.
  position: right
  # position: right
  # Replace the default avatar image and set the url here.
  avatar: tianci.jpg

widgets:
  # if true, will show random posts
  random_posts: true
  # if true, will show recent comments
  recent_comments: false

# é¡µå°¾å…¨ç«™ç»Ÿè®¡
footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2020
  icon:
    name: sakura rotate
    # Change the color of icon, using Hex Code.
    color: "#ffc0cb"
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: false
  powered: true

# æ–‡ç« ç•Œé¢ç»Ÿè®¡
post:
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: false

# Reward (Donate)
reward:
  # If true, reward will be displayed in every article by default.
  enable: true
  account:
    wechatpay: /wechatpay.png
    alipay: /alipay.jpg
    #paypal: /paypal.png

# TagCloud settings for tags page.
tagcloud:
  # All values below are same as default, change them by yourself.
  min: 16 # Minimun font size in px
  max: 22 # Maxium font size in px
  start: "#72cecf" # Start color (hex, rgba, hsla or color keywords)
  end: "#ffbac3" # End color (hex, rgba, hsla or color keywords)
  amount: 200 # Amount of tags, change it if you have more than 200 tags


# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

# Creative Commons 4.0 International License.
# See: https://creativecommons.org/share-your-work/licensing-types-examples
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
# CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
creative_commons:
  license: by-nc-sa
  language: deed.zh

# Comments
# Valine
# For more information: https://github.com/amehime/MiniValine
valine:
  appId: cbSBY3q77EE1UpivdrbefIqi-MdYXbMMI
  appKey: RD6UuwP5oeceYmtT0Exdjs5w
  placeholder: ãƒ½(â—‹Â´âˆ€`)ï¾‰â™ª # Comment box placeholder
  avatar: mp # Gravatar style : mp, identicon, monsterid, wavatar, robohash, retro
  pageSize: 10 # Pagination size
  lang: zh-CN
  visitor: true # Article reading statistic
  NoRecordIP: false # Whether to record the commenter IP
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  powerMode: true
  tagMeta:
    visitor: æ–°æœ‹å‹
    master: ä¸»äºº
    friend: å°ä¼™ä¼´
    investor: é‡‘ä¸»ç²‘ç²‘
  tagColor:
    master: "#855194"
    friend: "#a77c59"
    investor: "#ed6ea0"
  tagMember:
    master:
      # - hash of master@email.com
      # - hash of master2@email.com
    friend:
      # - hash of friend@email.com
      # - hash of friend2@email.com
    investor:
      # - hash of investor1@email.com
  placeholder: "1. æé—®å‰è¯·å…ˆä»”ç»†é˜…è¯»æœ¬æ–‡æ¡£âš¡\n2. é¡µé¢æ˜¾ç¤ºé—®é¢˜ğŸ’¥ï¼Œè¯·æä¾›æ§åˆ¶å°æˆªå›¾ğŸ“¸æˆ–è€…æ‚¨çš„æµ‹è¯•ç½‘å€\n3. å…¶ä»–ä»»ä½•æŠ¥é”™ğŸ’£ï¼Œè¯·æä¾›è¯¦ç»†æè¿°å’Œæˆªå›¾ğŸ“¸ï¼Œç¥é£Ÿç”¨æ„‰å¿«ğŸ’ª"
# bgm
audio:
  - https://y.qq.com/n/yqq/playlist/7361885581.html
  - https://y.qq.com/n/yqq/playlist/2742570554.html
  - https://music.163.com/#/playlist?id=4991304209

# random image api
image_server: # "https://acg.xydwz.cn/api/api.php"

# Dependencies: https://github.com/amehime/hexo-renderer-multi-markdown-it
pangu: false

# Quicklink Support
# For more information: https://github.com/GoogleChromeLabs/quicklink
quicklink:
  # Custom a time in milliseconds by which the browser must execute prefetching.
  timeout: 3000
  # Default (true) will attempt to use the fetch() API if supported (rather than link[rel=prefetch]).
  priority: true

  # For more flexibility you can add some patterns (RegExp, Function, or Array) to ignores.
  # See: https://github.com/GoogleChromeLabs/quicklink#custom-ignore-patterns
  ignores:

# ---------------------------------------------------------------
# analytics & SEO Settings
# ---------------------------------------------------------------
baidu_analytics: # <app_id>

# Disable Baidu transformation on mobile devices.
disable_baidu_transformation: true

# Automatically add external URL with Base64 encrypt & decrypt.
exturl: true

# Google Webmaster tools verification.
# See: https://www.google.com/webmasters
google_site_verification:

# Bing Webmaster tools verification.
# See: https://www.bing.com/webmaster
bing_site_verification:

# Yandex Webmaster tools verification.
# See: https://webmaster.yandex.ru
yandex_site_verification:

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO.
baidu_push: false


#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING `vendors` SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! Script dependencies will be combined with jsDelivr (cdn.jsdelivr.net)
#! ---------------------------------------------------------------
vendors:
  css:
    katex: npm/katex@0.12.0/dist/katex.min.css
    comment: css/comment.css
    fancybox: combine/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css,npm/justifiedGallery@3.8.1/dist/css/justifiedGallery.min.css
  js:
    pace: npm/pace-js@1.0.2/pace.min.js
    pjax: npm/pjax@0.2.8/pjax.min.js
    fetch: npm/whatwg-fetch@3.4.0/dist/fetch.umd.min.js
    anime: npm/animejs@3.2.0/lib/anime.min.js
    algolia: npm/algoliasearch@4/dist/algoliasearch-lite.umd.js
    instantsearch: npm/instantsearch.js@4/dist/instantsearch.production.min.js
    lazyload: npm/lozad@1/dist/lozad.min.js
    quicklink: npm/quicklink@2/dist/quicklink.umd.js
    fancybox: combine/npm/jquery@3.5.1/dist/jquery.min.js,npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js,npm/justifiedGallery@3.8.1/dist/js/jquery.justifiedGallery.min.js
    valine: gh/2016838087/TianciShokaCode@master/themes/shoka/source/js/MiniValine.min.js
    copy_tex: npm/katex@0.12.0/dist/contrib/copy-tex.min.js
    chart: npm/frappe-charts@1.5.0/dist/frappe-charts.min.iife.min.js

markdown:
  render: # æ¸²æŸ“å™¨è®¾ç½®
    html: false # è¿‡æ»¤ HTML æ ‡ç­¾
    xhtmlOut: true # ä½¿ç”¨ '/' æ¥é—­åˆå•æ ‡ç­¾ ï¼ˆæ¯”å¦‚ <br />ï¼‰ã€‚
    breaks: true # è½¬æ¢æ®µè½é‡Œçš„ '\n' åˆ° <br>ã€‚
    linkify: true # å°†ç±»ä¼¼ URL çš„æ–‡æœ¬è‡ªåŠ¨è½¬æ¢ä¸ºé“¾æ¥ã€‚
    typographer: 
    quotes: 'â€œâ€â€˜â€™'
  plugins: # markdown-it æ’ä»¶è®¾ç½®
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # æ–‡ç« ç›®å½•ä»¥åŠé”šç‚¹åº”ç”¨çš„ class åç§°ï¼Œshoka ä¸»é¢˜å¿…é¡»è®¾ç½®æˆè¿™æ ·
          tocClassName: 'toc'
          anchorClassName: 'anchor'
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: "()"
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: "ä½ çŸ¥é“å¾—å¤ªå¤šäº†"

# å‹ç¼©é™æ€æ–‡ä»¶
# minify:
#   html:
#     enable: false
#     exclude: # æ’é™¤ hexo-feed ç”¨åˆ°çš„æ¨¡æ¿æ–‡ä»¶
#       - '**/json.ejs'
#       - '**/atom.ejs'
#       - '**/rss.ejs'
#   css:
#     enable: false
#     exclude:
#       - '**/*.min.css'
#   js:
#     enable: false
#     mangle:
#       toplevel: true
#     output:
#     compress:
#     exclude:
#       - '**/*.min.js'

# åœç”¨ä»£ç é«˜äº®
highlight:
  enable: false
prismjs:
  enable: false

# ç¼ºå°‘è¿™ä¸ªæ’ä»¶ï¼Œé¦–é¡µå¡ç‰‡ç¿»è½¬æ•ˆæœåœ¨éƒ¨åˆ†æµè§ˆå™¨ä¸­æ— æ³•æ­£ç¡®æ˜¾ç¤ºã€‚
autoprefixer:
  exclude:
    - '*.min.css'

